[package]
name = "console_logify"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]
edition = "2021"

[dependencies]
ressa = "0.9.0-alpha.2"
atty = "0.2"
resw = "0.7.0-alpha.1"
resast = "0.6.0-alpha.3"
